Update dependencies of generated projects and add support for null safety in rx_bloc_cli
Prime-Holding/rx_bloc pull request #147
Opened 2021-05-25 13:54 UTC by DDavidPrime

2021-05-25 13:56 UTC, DDavidPrime commented
This PR resolves issue #126 .

2021-05-26 11:21 UTC, StanevPrime requested changes
Running "flutter pub get" in test_app...                        


Because test >=1.17.0 depends on test_api 0.4.0 and test >=1.16.7 <1.17.0 depends on test_api 0.3.0, test >=1.16.7 requires test_api 0.3.0 or 0.4.0.
And because every version of flutter_test from sdk depends on test_api 0.2.19, flutter_test from sdk is incompatible with test >=1.16.7.
So, because test_app depends on both flutter_test any from sdk and test ^1.16.8, version solving failed.
pub get failed (1; So, because test_app depends on both flutter_test any from sdk and test ^1.16.8, version solving failed.)

2021-05-26 15:12 UTC, DDavidPrime reviewed
Mentioned issues fixed. However, because of [this issue](https://github.com/dart-lang/sdk/issues/46136) we are temporary forced to use an older version of the `analyzer` package, until the `flutter_test` package from the `flutter sdk` gets updated.

2021-05-28 10:44 UTC, StanevPrime approved these changes

2021-05-28 10:46 UTC, merged