Add refresh done state on dashboard page
Prime-Holding/rx_bloc pull request #238
Opened 2022-05-10 06:38 UTC by StanislavPrime

Unify behaviour on both pages, so that when we make a pull to refresh on DashboardPage the loading indication is the same as in the ReminderListPage.

2022-05-10 07:56 UTC, StanevPrime requested changes

2022-05-10 07:56 UTC, StanevPrime commented on examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc_extensions.dart
> +    await Future.delayed(const Duration(milliseconds: 2000));
Please implement this method

2022-05-12 07:47 UTC, StanevPrime approved these changes

2022-05-12 18:28 UTC, StanislavPrime commented on examples/reminders/lib/feature_dashboard/blocs/dashboard_bloc_extensions.dart
> +    await Future.delayed(const Duration(milliseconds: 2000));
The method was implemented

2022-05-13 06:57 UTC, merged