Add SSE communication facilities template to rx_block_cli
Prime-Holding/rx_bloc pull request #512
Opened 2023-05-12 15:26 UTC by kostadin-damyanov-prime

2023-05-12 15:38 UTC, StanevPrime requested changes
Please document the changes in the rx_bloc_cli

2023-05-13 15:58 UTC, kostadin-damyanov-prime commented
> Please document the changes in the rx_bloc_cli

Updated CHANGELOG.md

2023-05-13 21:36 UTC, StanevPrime requested changes
Could you please add a section using the moustache condition In the read me file? I guess this will be a good starting point from tech documentation perspective for the apps that need real time updates.

2023-05-13 21:36 UTC, StanevPrime commented on packages/rx_bloc_cli/CHANGELOG.md
> +* Added SSE communication facilities template
Let's ship the see and the patrol integration in one release

2023-05-15 10:11 UTC, merged