Feature: Dart 3 updates to rx_bloc
Prime-Holding/rx_bloc pull request #535
Opened 2023-06-23 12:48 UTC by PetkovPrime

### Description
The pull request closes #532

2023-07-03 11:44 UTC, PrimeSwiftArt reviewed
I thing all xml files inside `.run` should be ignored and not be in the repo.

2023-07-03 11:44 UTC, PrimeSwiftArt commented on packages/rx_bloc_test/pubspec.yaml
> +version: 3.4.0
Increment `major` version number instead of the `minor` one. Because this package is requiring Dart to be 3.0+.

2023-07-10 06:23 UTC, PetkovPrime commented
> I thing all xml files inside `.run` should be ignored and not be in the repo.

I added them because I saw that the `rx_bloc_cli` package has the compile / compile bundles added and I thought it would be easier for the developers to have a run action for the unit tests and example applications.

If you think there's a drawback to having them stored, I'll going to remove them.

2023-07-10 08:11 UTC, PrimeSwiftArt commented
> > I thing all xml files inside `.run` should be ignored and not be in the repo.
> 
> I added them because I saw that the `rx_bloc_cli` package has the compile / compile bundles added and I thought it would be easier for the developers to have a run action for the unit tests and example applications.
> 
> If you think there's a drawback to having them stored, I'll going to remove them.

@DDavidPrime can you give us your opinion about this?

2023-07-11 11:04 UTC, PrimeSwiftArt requested changes

2023-07-11 11:04 UTC, PrimeSwiftArt commented on packages/rx_bloc/CHANGELOG.md
> +* Support Dart `3.0`
Dart 3.0 is required

2023-07-11 11:04 UTC, PrimeSwiftArt commented on packages/rx_bloc_generator/CHANGELOG.md
> +* Support Dart 3.0
Dart 3.0 is required.

2023-07-11 11:04 UTC, PrimeSwiftArt commented on packages/rx_bloc_test/CHANGELOG.md
> +* Support Dart `3.0`
Dart 3.0 is required.

2023-07-11 11:04 UTC, PrimeSwiftArt commented on packages/rx_bloc_list/CHANGELOG.md
> +* Support Dart `3.0`
Dart 3.0 is required.

2023-07-11 12:56 UTC, PrimeSwiftArt approved these changes

2023-07-11 13:21 UTC, merged