Update create command to allow interactive input
Prime-Holding/rx_bloc pull request #556
Opened 2023-08-04 15:52 UTC by PetkovPrime

2023-08-07 12:06 UTC, PrimeSwiftArt requested changes

2023-08-07 12:54 UTC, PetkovPrime commented on packages/rx_bloc_cli/lib/src/extensions/arg_results_extensions.dart
> +  bool? readBool(String name) => readString(name)?.toBool();
Updated

2023-08-07 13:37 UTC, PrimeSwiftArt approved these changes

2023-08-08 07:06 UTC, JvnSlv approved these changes

2023-08-09 11:06 UTC, PrimeSwiftArt approved these changes

2023-08-09 12:21 UTC, JvnSlv approved these changes

2023-08-09 12:23 UTC, merged