Update go_router and go_router builder versions
Prime-Holding/rx_bloc pull request #560
Opened 2023-08-11 08:02 UTC by PetkovPrime

Closes #557

2023-08-11 12:22 UTC, PrimeSwiftArt requested changes

2023-08-11 12:22 UTC, PrimeSwiftArt commented on packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/feature_home/views/home_page.dart
> +              opacity: index == currentIndex ? 1 : 0,
Create a local variable for `index == currentIndex` and use it everywhere in this mapper body.

2023-08-11 12:22 UTC, PrimeSwiftArt commented on packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml
Are the all dependencies upgraded to their latest versions?

2023-08-14 04:32 UTC, PrimeSwiftArt approved these changes

2023-08-16 14:11 UTC, StanislavPrime approved these changes

2023-08-16 14:15 UTC, merged