668 - Remove specifics and add more general components to the architecture diagram
Prime-Holding/rx_bloc pull request #669
Opened 2024-03-27 14:28 UTC by RomanovaPrime

Remove specifics and add more general components to the architecture diagram

#### Overview

> Closes: < 668 >

< Pull Request Description >

#### Checklist

*Implementation*
- [ ] Implementation matches ticket acceptance criteria and technical notes
- [ ] Manually tested against Acceptance Criteria
- [ ] UI checked in Light / Dark mode

*Stability*
- [ ] Checked if changes affect any features and verified affected features work as expected
- [ ] Added unit tests for new code and verified existing tests work as expected

*Code quality*
- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`
- [ ] Dependencies are updated to latest versions or new tickets are created if there are breaking changes or deprecations
- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes

2024-03-27 14:37 UTC, StanevPrime requested changes

2024-03-27 14:37 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/docs/app_architecture.png
<img width="605" alt="image" src="https://github.com/Prime-Holding/rx_bloc/assets/32831935/61af72ff-b31d-4e15-8355-07346d86843f">
Do we really want such high resolution ?

2024-03-27 14:45 UTC, DDavidPrime approved these changes

2024-03-28 07:29 UTC, RomanovaPrime commented on packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/docs/app_architecture.png
I have reduced the image size to be similar to the previous image

2024-03-28 07:48 UTC, StanevPrime requested changes
Please make sure that you complete this action item

Updated CHANGELOG.md, README.md

2024-03-28 08:17 UTC, RomanovaPrime commented
> Please make sure that you complete this action item
> 
> Updated CHANGELOG.md, README.md

Since I haven't change the file name, I believe we do not need any changes in README.md. 
As per CHANGELOG.md, I believe that this can be considered as documentation, so "Documentation and stability improvements" describes it enough. 
Do you, however, want me to add or change something?

2024-03-28 08:21 UTC, StanevPrime commented
> > Please make sure that you complete this action item
> > Updated CHANGELOG.md, README.md
> 
> Since I haven't change the file name, I believe we do not need any changes in README.md. As per CHANGELOG.md, I believe that this can be considered as documentation, so "Documentation and stability improvements" describes it enough. Do you, however, want me to add or change something?

@DDavidPrime, @RomanovaPrime please add specifics for the documentation changes part of the change log

2024-03-28 09:09 UTC, StanevPrime approved these changes

2024-03-28 09:25 UTC, merged