Merge develop to master
Prime-Holding/rx_bloc pull request #701
Opened 2024-06-26 08:47 UTC by DDavidPrime

2024-06-26 08:51 UTC, StanevPrime commented
@DDavidPrime please organise a demo session before we merge this PR. Last but not least the solution needs to be tested from someone from the team to ensure that meets the needed quality.

2024-06-26 08:56 UTC, StanevPrime requested changes

2024-06-26 08:56 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/docs/continuous_delivery.md
> +If the project was generated with the `--cicd=codemagic` flag, a `codemagic.yaml` file is created within the root of the project.
Please list all available workflows and their purpose

2024-06-26 08:56 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_cicd_fastlane/__brick__/fastlane/Fastfile
> +                workspace: PROJECT_PATH_ABS+'/ios/Runner.xcworkspace',
Please confirm this works with 

1. Local distribution
2. Github Actions
3. CodeMagic

2024-06-26 10:06 UTC, JvnSlv commented on packages/rx_bloc_cli/example/docs/continuous_delivery.md
Line 18.
`Before committing any changes, make sure you encrypt all the files using the `./crypto.sh encode all` command.`
The file is called `crypt.sh` either rename the file or change the documentation

2024-06-26 10:19 UTC, JvnSlv commented
Running `rx_bloc_cli create_distribution .` overwrites the `README.md` created by the `rx_bloc_cli create` command which I think shouldn't be the case.
We should have something like:
README.md 
README_DISTRIBUTION.md

2024-06-26 15:23 UTC, DDavidPrime commented
> Running `rx_bloc_cli create_distribution .` overwrites the `README.md` created by the `rx_bloc_cli create` command which I think shouldn't be the case. We should have something like: README.md README_DISTRIBUTION.md

How and where does this happen? The `rx_bloc_cli create_distribution .` and `rx_bloc_cli create .` should not be generated within the same directory. Since they are distinct commands, the intention is to create a separate repo for the project and the credentials, thus being two separate directories. This way there should never be a collision between the readme files.

Was that what you meant or was it some other scenario you encountered where the files were getting replaced.

2024-06-27 07:40 UTC, StanevPrime approved these changes

2024-06-28 23:17 UTC, merged