Implement rest api into the todo app
Prime-Holding/rx_bloc pull request #753
Opened 2024-07-19 10:01 UTC by JvnSlv

#### Overview

> Closes: < issue >

< Pull Request Description >

#### Checklist

*Implementation*
- [ ] Implementation matches ticket acceptance criteria and technical notes
- [ ] Manually tested against Acceptance Criteria
- [ ] UI checked in Light / Dark mode

*Stability*
- [ ] Checked if changes affect any features and verified affected features work as expected
- [ ] Added unit tests for new code and verified existing tests work as expected

*Code quality*
- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`
- [ ] Dependencies are updated to latest versions or new tickets are created if there are breaking changes or deprecations
- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes

2024-07-19 11:01 UTC, StanevPrime requested changes

2024-07-19 11:56 UTC, StanevPrime approved these changes
Please make sure you test the application carefully, since as of know it has been using in-memory storage. With that being said the error and loading states might need additional work

2024-07-24 10:00 UTC, StanevPrime requested changes

2024-07-24 10:00 UTC, StanevPrime commented on examples/todoapp/lib/feature_todo_management/views/todo_management_page.dart
> +                    : const Center(child: CircularProgressIndicator()),
Can't we use some of the app-specific widgets such as `AppLoadingIndicator` ?

2024-07-24 10:03 UTC, JvnSlv commented on examples/todoapp/lib/feature_todo_list/views/todo_list_page.dart
> +              RxBlocBuilder<TodoActionsBlocType, bool>(
Updating todos completed status is handled by `TodoActionsBlocType`. So here the simplest solution for me was to listen to isLoading state from `TodoActionsBlocType`

2024-07-24 11:10 UTC, StanevPrime commented on examples/todoapp/lib/feature_todo_list/views/todo_list_page.dart
> +              RxBlocBuilder<TodoActionsBlocType, bool>(
I see.

2024-07-24 11:39 UTC, StanevPrime requested changes

2024-07-24 11:39 UTC, StanevPrime commented on examples/todoapp/lib/feature_todo_list/views/todo_list_page.dart
> +              RxBlocBuilder<TodoActionsBlocType, bool>(
As discussed the checkbox disabled state needs to be implemented instead of the loading representation

2024-07-25 06:18 UTC, StanevPrime approved these changes

2024-07-25 08:15 UTC, merged