Server endpoints for PIN create, verify & update
Prime-Holding/rx_bloc pull request #790
Opened 2024-08-28 07:59 UTC by GoranPrime

#### Overview

> Closes: #609 

< Pull Request Description >

#### Checklist

*Implementation*
- [x] Implementation matches ticket acceptance criteria and technical notes
- [x] Manually tested against Acceptance Criteria
- [x] UI checked in Light / Dark mode

*Stability*
- [x] Checked if changes affect any features and verified affected features work as expected
- [ ] Added unit tests for new code and verified existing tests work as expected

*Code quality*
- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`
- [ ] Dependencies are updated to latest versions or new tickets are created if there are breaking changes or deprecations
- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes

2024-09-04 07:48 UTC, GoranPrime commented on packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/services/update_and_verify_pin_code_service.dart
> +  late String token;
Good catch!

2024-09-04 07:48 UTC, GoranPrime commented on packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/data_source/remote/pin_code_data_source.dart
> +  @PATCH('/api/pin/create')
You're right, using `POST` or `PUT` is correct here. I've changed it

2024-09-04 07:48 UTC, GoranPrime commented on packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/bin/server/controllers/pin_code_controller.dart
> +  final Map<String, String> _tokens = {};
Good suggestion, added

2024-09-04 09:12 UTC, JvnSlv approved these changes

2024-09-04 09:33 UTC, StanevPrime requested changes

2024-09-18 07:33 UTC, GoranPrime commented on packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/repository/pin_code_repository.dart
> +  late String _token;
I've changed it to be a parameter in the `UpdatePinCodeService` constructor, instead of a state

2024-09-18 07:33 UTC, GoranPrime commented on packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/repository/pin_code_repository.dart
> +  Future<void> updatePinCode(String pinCode) => _errorMapper.execute(
Done

2024-09-18 07:33 UTC, GoranPrime commented on packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code/models/pin_code_verify_request.dart
> +  final String pinCode;
Done

2024-09-20 12:18 UTC, JvnSlv approved these changes

2024-09-20 13:11 UTC, merged