Feature/Extract lib_translations as brick
Prime-Holding/rx_bloc pull request #851
Opened 2024-11-01 15:37 UTC by GoranPrime

#### Overview

> Closes: #840 

Adds `enable-remote-translations` parameter to rx_bloc_cli

#### Checklist

*Implementation*
- [x] Implementation matches ticket acceptance criteria and technical notes
- [x] Manually tested against Acceptance Criteria
- [x] UI checked in Light / Dark mode

*Stability*
- [x] Checked if changes affect any features and verified affected features work as expected
- [x] Added unit tests for new code and verified existing tests work as expected

*Code quality*
- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`
- [ ] Dependencies are updated to latest versions or new tickets are created if there are breaking changes or deprecations
- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes

2024-11-04 07:08 UTC, StanevPrime requested changes

2024-11-04 07:08 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/lib/l10n/network_lookup/counter_lookup.dart
>  import '../../assets.dart';
My understanding is that the network_loopkup files are not needed in case the remote translations are not enabled.

2024-11-04 07:08 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_deeplink/__brick__/lib/l10n/network_lookup/deep_link_lookup.dart
> +import '../{{project_name}}_app_i18n.dart';{{#enable_remote_translations}}
My understanding is that the network_loopkup files are not needed in case the remote translations are not enabled.

2024-11-04 07:08 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_deeplink/__brick__/lib/l10n/network_lookup/enter_message_lookup.dart
> +import '../{{project_name}}_app_i18n.dart';{{#enable_remote_translations}}
My understanding is that the network_loopkup files are not needed in case the remote translations are not enabled.

2024-11-04 07:08 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_otp/__brick__/lib/l10n/network_lookup/otp_lookup.dart
> +import '../{{project_name}}_app_i18n.dart';{{#enable_remote_translations}}
My understanding is that the network_loopkup files are not needed in case the remote translations are not enabled.

2024-11-04 07:08 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_profile/__brick__/lib/l10n/network_lookup/profile_lookup.dart
> +import '../{{project_name}}_app_i18n.dart';{{#enable_remote_translations}}
My understanding is that the network_loopkup files are not needed in case the remote translations are not enabled.

2024-11-04 07:08 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_qr_scanner/__brick__/lib/l10n/network_lookup/qr_code_lookup.dart
> +import '../{{project_name}}_app_i18n.dart';{{#enable_remote_translations}}
My understanding is that the network_loopkup files are not needed in case the remote translations are not enabled.

2024-11-04 15:30 UTC, StanevPrime commented on packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/lib/l10n/network_lookup/counter_lookup.dart
>  import '../../assets.dart';
My understanding is that we need the lookup only if the translations needs to be adjusted from the API. Is that correct statement ?

2024-11-06 13:19 UTC, StanevPrime approved these changes

2024-11-06 13:37 UTC, StanevPrime approved these changes

2024-11-06 14:36 UTC, DDavidPrime approved these changes

2024-11-06 14:59 UTC, merged

2024-11-12 13:19 UTC, JvnSlv commented
Tested, everything works

The only thing that when the cli displays which features are used, the remote translations is not present

![Screenshot 2024-11-12 at 14 17 16](https://github.com/user-attachments/assets/7d9340b1-2a10-4606-b4bc-5e4ba4f03380)

2024-11-14 11:34 UTC, GoranPrime commented
> Tested, everything works
> 
> The only thing that when the cli displays which features are used, the remote translations is not present
> 
> ![Screenshot 2024-11-12 at 14 17 16](https://private-user-images.githubusercontent.com/122014682/385298328-7d9340b1-2a10-4606-b4bc-5e4ba4f03380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDY3MzcsIm5iZiI6MTczMTU0NjQzNywicGF0aCI6Ii8xMjIwMTQ2ODIvMzg1Mjk4MzI4LTdkOTM0MGIxLTJhMTAtNDYwNi1iNGJjLTVlNGJhNGYwMzM4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwMTA3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDg5Nzg1N2FlYzg4YzBiZjcwOGMwMmE0MThkMTU4YjFkMTE2NTJhODRmMzcxNzYzYjIxZWVjOTFiYmIwZTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qogAdd0uCJXOupQ5lGL4FWbnI04VTDpLpPdFP_hu0ZQ)

Good catch, I've fixed it here:
https://github.com/Prime-Holding/rx_bloc/pull/877