Update booking app goldens to use alchemist
Prime-Holding/rx_bloc pull request #884
Opened 2024-11-19 08:06 UTC by nikolay-vasilev-prime

#### Overview

> Closes: 865

#### Checklist

*Implementation*
- [ ] Implementation matches ticket acceptance criteria and technical notes
- [ ] Manually tested against Acceptance Criteria
- [ ] UI checked in Light / Dark mode

*Stability*
- [ ] Checked if changes affect any features and verified affected features work as expected
- [ ] Added unit tests for new code and verified existing tests work as expected

*Code quality*
- [ ] Updated `CHANGELOG.md`, `README.md` and package versions in `pubspec.yaml`
- [ ] Dependencies are updated to latest versions or new tickets are created if there are breaking changes or deprecations
- [ ] If an unrelated part of the codebase needs to be updated or refactored, create tickets with proposed changes

2024-11-19 10:05 UTC, StanevPrime requested changes

2024-11-19 10:05 UTC, StanevPrime commented on examples/booking_app/test/feature_home/view/home_page_golden_test.dart
> +      customPumpBeforeTest: animationCustomPump,
@GoranPrime it looks that here the animationCustomPump works as expected

2024-11-19 10:05 UTC, StanevPrime commented on examples/booking_app/test/feature_hotel_favorites/view/goldens/linux/dark_theme/hotel_favorites_success.png
Do we really want to commit platform-specific golden files ?

2024-11-19 10:05 UTC, StanevPrime commented on examples/booking_app/test/feature_hotel_search/view/goldens/ci/dark_theme/hotel_animated_list_view_with_hotels.png
Why here we have a blank page ?

2024-11-19 14:35 UTC, nikolay-vasilev-prime commented on examples/booking_app/test/feature_hotel_favorites/view/goldens/linux/dark_theme/hotel_favorites_success.png
This is fixed

2024-11-20 20:13 UTC, StanevPrime approved these changes

2024-11-21 08:47 UTC, merged